#-------------------------------
# General Site Settings
title: JPaulMora's Blog
logo: logo.png # You can add own logo.
description: Blog & Personal Wiki, Enjoy!

#-------------------------------
# Author Settings
author:
  name: Juan Pablo Mora
  image: 8335656.jpeg
  say-hello: Hello, Iâ€™m <strong>Juan Pablo Mora</strong>
  bio: I write about <strong>tech</strong>, <strong>programming</strong>, <strong>privacy</strong> and <strong>hacking</strong>, among other related topics. I share IT and programming tutorials, free resources and inspiration. Love <a href="https://soundcloud.com/juan-pa-mora">music</a> & running.

#-------------------------------
# Contact links
twitter: https://twitter.com/JPaulMora # Add your Twitter handle
instagram: https://instagram.com/JPaulMora # Add your Instagram handle
tiktok: https://www.tiktok.com/@jpaulmora


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: jpaulmora-github # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: JPaulMora # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-161557905-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
newsletter: false
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e